<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIV43qNr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIV43qNr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIV43qNr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIV43qNr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIV43qNr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IV43qNr',
    'container.build_id' => 'f6591f3f',
    'container.build_time' => 1579049651,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIV43qNr');
