<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPb7RiSy\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPb7RiSy/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPb7RiSy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPb7RiSy\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerPb7RiSy\srcApp_KernelProdContainer([
    'container.build_hash' => 'Pb7RiSy',
    'container.build_id' => 'a2990c0f',
    'container.build_time' => 1577804955,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPb7RiSy');
