<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'AdminSection' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/adminSection']], [], []],
    'showAllProfil' => [[], ['_controller' => 'App\\Controller\\AdminController::showProfil'], [], [['text', '/adminSection/showProfil']], [], []],
    'showAllUser' => [[], ['_controller' => 'App\\Controller\\AdminController::showUser'], [], [['text', '/adminSection/showUser']], [], []],
    'showAllSandwich' => [[], ['_controller' => 'App\\Controller\\AdminController::showSandwich'], [], [['text', '/adminSection/showSandwich']], [], []],
    'showAllIngredient' => [[], ['_controller' => 'App\\Controller\\AdminController::showIngredient'], [], [['text', '/adminSection/showIngredient']], [], []],
    'showAllBread' => [[], ['_controller' => 'App\\Controller\\AdminController::showBread'], [], [['text', '/adminSection/showBread']], [], []],
    'showAllJuice' => [[], ['_controller' => 'App\\Controller\\AdminController::showJuice'], [], [['text', '/adminSection/showJuice']], [], []],
    'showAllMenu' => [[], ['_controller' => 'App\\Controller\\AdminController::showMenu'], [], [['text', '/adminSection/showMenu']], [], []],
    'CrockSan' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
];
