<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUFt4Oxs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUFt4Oxs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUFt4Oxs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUFt4Oxs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUFt4Oxs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UFt4Oxs',
    'container.build_id' => '0dc11977',
    'container.build_time' => 1579065934,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUFt4Oxs');
